namespace Ais.Net.Radius.Attributes
{
    /// <summary>
    /// Type of radius attribute.
    /// </summary>
    public enum AttributeType
    {
        Unknown = 0,
        UserName = 1,
        UserPassword = 2,
        ChapPassword = 3,
        NasIpAddress = 4,
        NasPort = 5,
        ServiceType = 6,
        FramedProtocol = 7,
        FramedIpAddress = 8,
        FramedIpNetmask = 9,
        FramedRouting = 10,
        FilterId = 11,
        FramedMtu = 12,
        FramedCompression = 13,
        LoginIpHost = 14,
        LoginService = 15,
        LoginTcpPort = 16,
        ReplyMessage = 18,
        CallbackNumber = 19,
        CallbackId = 20,
        FramedRoute = 22,
        FramedIpxNetwork = 23,
        State = 24,
        Class = 25,
        VendorSpecific = 26,
        SessionTimeout = 27,
        IdleTimeout = 28,
        TerminationAction = 29,
        CalledStationId = 30,
        CallingStationId = 31,
        NasIdentifier = 32,
        ProxyState = 33,
        LoginLatService = 34,
        LoginLatNode = 35,
        LoginLatGroup = 36,
        FramedAppleTalkLink = 37,
        FramedAppleTalkNetwork = 38,
        FramedAppleTalkZone = 39,
        AcctStatusType = 40,
        AcctDelayTime = 41,
        AcctInputOctets = 42,
        AcctOutputOctets = 43,
        AcctSessionId = 44,
        AcctAuthentic = 45,
        AcctSessionTime = 46,
        AcctInputPackets = 47,
        AcctOutputPackets = 48,
        AcctTerminateCause = 49,
        AcctMultiSessionId = 50,
        AcctLinkCount = 51,
        ChapChallenge = 60,
        NasPortType = 61,
        PortLimit = 62,
        LoginLatPort = 63,
    }
}
